# Generated by Django 5.1.6 on 2025-02-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
