# Generated by Django 5.1.6 on 2025-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_otp_customuser_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_tries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
