# Generated by Django 5.1.6 on 2025-02-22 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_sub_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('fee_for_member', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_for_external', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_ends', models.DateTimeField()),
                ('event_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
